version: "3.5"

services:
  api01: &api
    image: ghcr.io/4emcos/pixel-pay:latest
    hostname: api01
    environment:
        - DB_HOST=db
        - AUTHORIZER_HOST=auth_notification
        - NOTIFICATION_HOST=auth_notification
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.37"
          memory: "55MB"

  api02:
    <<: *api
    hostname: api02

  auth_notification:
    image: ghcr.io/4emcos/pixel-pay-authorizer-notification:latest
    hostname: auth_notification
    ports:
      - "8099:8099"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./devops/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=oot123
      - POSTGRES_USER=admin
      - POSTGRES_DB=pixel_pay
    ports:
      - "5432:5432"
    volumes:
      - ./devops/sql/ddl.sql:/docker-entrypoint-initdb.d/script.sql
    deploy:
      resources:
        limits:
          cpus: "0.56"
          memory: "410MB"